/*
 * Copyright 2016 (C) Inwoo Chung (gutomitai@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maum_dm_Matrix */

#ifndef _Included_maum_dm_Matrix
#define _Included_maum_dm_Matrix
#ifdef __cplusplus
extern "C" {
#endif
#undef maum_dm_Matrix_serialVersionUID
#define maum_dm_Matrix_serialVersionUID -3942409404701938223LL
#undef maum_dm_Matrix_ACC_COMPUTING_MODE_NONE
#define maum_dm_Matrix_ACC_COMPUTING_MODE_NONE 0L
#undef maum_dm_Matrix_ACC_COMPUTING_MODE_CUDA
#define maum_dm_Matrix_ACC_COMPUTING_MODE_CUDA 1L
/*
 * Class:     maum_dm_Matrix
 * Method:    innerProductCUDA
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_maum_dm_Matrix_innerProductCUDA
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
